name: Checking
concurrency: 
  group: ci-workflow-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
env:
  GO_VERSION: 1.18

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: latest
          # skip cache because of flaky behaviors
          skip-build-cache: true
          skip-pkg-cache: true
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }} # The Go version to download (if necessary) and use.

      - name: Check out code
        uses: actions/checkout@v2
      - name: Vet
        run: go vet -v ./...
      - name: Run test
        run: make test


